#!/usr/bin/env php

<?php

ini_set('display_errors', 1);
ini_set('display_errors', 1);

require __DIR__.'/vendor/autoload.php';

$config = require __DIR__.'/app/configuration.php';

$conn = r\connect($config['RETHINK_HOST']);
$conn->useDb($config['RETHINK_DATABASE']);

$database = r\db($config['RETHINK_DATABASE']);

if(!isset($argv[1])){
    doDB($conn, $config, $database);
    doUsers($conn, $config, $database);
    doModules($conn, $config, $database);
    die();
}

switch($argv[1]){
  case 'help':
  case '--help':
    echo "Help may go here someday when we have time :)\n";
  case ('db'):
    doDB($conn, $config, $database);
  case ('users'):
    doUsers($conn, $config, $database);
    break;
  case ('modules'):
    doModules($conn, $config, $database);
    break;
  case ('all'):
    doDB($conn, $config, $database);
    doUsers($conn, $config, $database);
    doModules($conn, $config, $database);
    break;

}

function doDB($conn, $config, $database){
  try{
    r\dbCreate($config['RETHINK_DATABASE'])->run($conn);
    echo "Created db '{$config['RETHINK_DATABASE']}'\n";
  }catch(Exception $e){}
}

function doUsers($conn, $config, $database){
  // Create a test table

  try{
    $database->tableDrop("user")->run($conn);
    echo "Dropped table user\n";
  }catch(Exception $e){}

  $database->tableCreate("user")->run($conn);
  echo "Created table user\n";

  $spass = sha1('1234');

  $user1 = array('username' => "testuser", "first_name"=>"test", "last_name"=>"user", "password" => $spass, "email"=> "test@user.com", "isAdmin" => 1);
  $user2 = array('username' => "testuser2", "first_name"=>"test", "last_name"=>"user2", "password" => $spass, "email"=> "test@user2.com");

  $database->table('user')->insert($user1)->run($conn)->toNative();
  $database->table('user')->insert($user2)->run($conn)->toNative();

  echo "Created user => username: testuser, password: password\n";
  echo "Created user => username: testuser2, password: password\n";
}

function doModules($conn, $config, $database){
  try{
    $database->tableDrop("module")->run($conn);
    echo "Dropped table module\n";
  }catch(Exception $e){}
  try{
    $database->tableDrop("moduleQuiz")->run($conn);
    echo "Dropped table moduleQuiz\n";
  }catch(Exception $e){}
  try{
    $database->tableDrop("moduleQuestion")->run($conn);
    echo "Dropped table moduleQuestion\n";
  }catch(Exception $e){}
  try{
    $database->tableDrop("moduleUser")->run($conn);
    echo "Dropped table moduleUser\n";
  }catch(Exception $e){}

  $database->tableCreate("module")->run($conn);
  echo "Created table module\n";
  $database->tableCreate("moduleQuestion")->run($conn);
  echo "Created table moduleQuestion\n";
  $database->tableCreate("moduleUser")->run($conn);
  echo "Created table moduleUser\n";

  $module1 = array('name' => "Test Module 1", "description"=>"This is a short description of a module.", "text"=>"This is longer description<br>with html in it.", "video"=>"cat.mov");
  $reply = $database->table('module')->insert($module1)->run($conn)->toNative();
  $id = $reply['generated_keys'][0];
  $modq1 = array('moduleID'=>$id, 'text'=>'Is The Cat Cute?', 'correct'=>0, 'choices' => array(array('text'=>'Yes it is'), array('text'=>'No it is not'), array('text'=>'Cats are never cute on internet videos')));
  $reply = $database->table('moduleQuestion')->insert($modq1)->run($conn)->toNative();

  echo "Seeded module\n";
}